name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy API to cloudflare Workers
    steps:
      - uses: actions/checkout@v3
			- uses: dorny/paths-filter@v2
				id: changues
				with:
					filter: |
						- 'db/**'
						- 'api/**'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install npm dependecy
        run: npm ci
			- if: steps.changes.outputs.src == 'true'
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
